GET http://localhost:3000/book

###

GET http://localhost:3000/book/2

###

POST http://localhost:3000/book
Content-Type: application/json

{
    "genreId": 1,
    "authorId": 1,
    "title": "Test wypozyczenia",
    "pages": 12,
    "year": 12,
    "quantity": 2,
    "ISBN": "C",
    "cost": 12
}

###

DELETE http://localhost:3000/book/111

###

POST http://localhost:3000/genre
Content-Type: application/json

{
    "name": "Fiction 2",
    "description": "Some description"
}

###

PATCH http://localhost:3000/book/2
Content-Type: application/json

{
    "genreId": 1,
    "authorId": 1,
    "title": "Test 3",
    "pages": 12,
    "year": 12,
    "quantity": 2,
    "ISBN": "C",
    "cost": 12
}

###

POST http://localhost:3000/author
Content-Type: application/json

{
    "firstName": "Adam",
    "lastName": "Kowal"
}

###

GET http://localhost:3000/author/1

###
POST http://localhost:3000/loan
Content-Type: application/json

{
    "bookId": 2,
    "readerId": 7
}

### 
POST http://localhost:3000/reader
Content-Type: application/json

{
    "firstName": "Adam 1",
    "lastName": "Nowak 1",
    "telephone" : 123456789
}

###

POST http://localhost:3000/loan/6/return
Content-Type: application/json

###
GET http://localhost:3000/loan

###
GET http://localhost:3000/author/1

###
GET http://localhost:3000/user/books?limit=1&page=2
Content-Type: application/json

{
    "id": 1
}