version: "3"
services:
  db:
    image: mariadb:10.7.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "${TYPEORM_PORT}:${TYPEORM_PORT}"
    environment:
      MYSQL_TCP_PORT: ${TYPEORM_PORT}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${TYPEORM_DATABASE}
      MARIADB_USER: ${TYPEORM_USERNAME}
      MARIADB_PASSWORD: ${TYPEORM_PASSWORD}
  
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8090:8080
